import React from 'react';

const doctor = () => {
    return (
        <div>
            <table className = "schedule">
                <thead>
                <tr>
                    <th>Time\Day</th>
                    <th>Sunday</th>
                    <th>Monday</th>
                    <th>Tuesday</th>
                    <th>Wednesday</th>
                    <th>Thursday</th>
                    <th>Friday</th>
                    <th>Saturday</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>09:00-09:30</td>
                </tr>
                <tr>
                    <td>09:30-10:00</td>
                </tr>
                <tr>
                    <td>10:00-10:30</td>
                </tr>
                <tr>
                    <td>10:30-11:00</td>
                </tr>
                <tr>
                    <td>11:00-11:30</td>
                </tr>
                <tr>
                    <td>11:30-12:00</td>
                </tr>
                <tr>
                    <td>12:00-12:30</td>
                </tr>
                <tr>
                    <td>12:30-13:00</td>
                </tr>
                <tr>
                    <td>13:00-13:30</td>
                </tr>
                <tr>
                    <td>13:30-14:00</td>
                </tr>
                <tr>
                    <td>14:00-14:30</td>
                </tr>
                <tr>
                    <td>14:30-15:00</td>
                </tr>
                <tr>
                    <td>15:00-15:30</td>
                </tr>
                <tr>
                    <td>15:30-16:00</td>
                </tr>
                <tr>
                    <td>16:00-16:30</td>
                </tr>
                <tr>
                    <td>16:30-17:00</td>
                </tr>
                <tr>
                    <td>17:00-17:30</td>
                </tr>
                <tr>
                    <td>17:30-18:00</td>
                </tr>
                </tbody>
            </table>
        </div>
    )
}
export default doctor;
